core/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, add_to_cart, remove_from_cart, OrderSummaryView, decrease_item_from_cart, increase_item_in_cart, CheckoutView, PaymentView

app_name = 'core' 

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # path('checkout/', check, name='check'),
    path('checkout', CheckoutView.as_view(), name='check'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_to_cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('decrease_item_from_cart/<slug>', decrease_item_from_cart, name='decrease_item_from_cart'),
    path('increase_item_in_cart/<slug>', increase_item_in_cart, name='increase_item_in_cart'),
    # path('add_to_whishlist/<slug>', add_to_whishlist, name='add_to_whishlist'),
    # path('wishist/', WishList.as_view(), name='wishlist')
    path('payment/<payment_option>', PaymentView.as_view(), name='payment'),
]
 

e-comm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='login'),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Phone'),
    ('SW', 'Laptop'),
    ('OW', 'Tablet'),
    ('T', 'TV'),
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

class Item(models.Model):
    image = models.ImageField(blank=True, null=True)
    title = models.CharField(max_length=256)
    price = models.FloatField()
    discounted_price = models.FloatField(blank=True, null=True)
    description=models.TextField(blank=True, null=True)

    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)

    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={'slug':self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={'slug':self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={'slug':slug})



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey('Item', on_delete=models.CASCADE, null=True)
    
    quantity = models.IntegerField(default=1)           #gets the count of the items ordered

    def __str__(self):
        return f"{self.quantity} of {self.item.title}, user: {self.user}"

    def get_total_price(self):
        return self.quantity * self.item.price
    def get_total_price_discount(self):
        return self.quantity * self.item.discounted_price
    def get_price_saved(self):
        return self.get_total_price() - self.get_total_price()

    def get_final_price(self):
        if self.item.discounted_price:
            return self.get_total_price_discount()
        return self.get_total_price()

    def get_total_actual_price(self):
        return self.get_total_price()




class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)    
    start_date=models.DateTimeField(auto_now_add=True)
    order_date=models.DateTimeField()
    ordered=models.BooleanField(default=False)

    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total_price = 0
        for item_price in self.items.all():
            total_price += item_price.get_final_price()
        return total_price

    def get_total_actual(self):                         # total final price
        total_price = 0
        for item_price in self.items.all():
            total_price += item_price.get_total_actual_price()
        return total_price - self.get_total()

    def get_extra_discount(self):                       # if final price is > 5000
        final_price = self.get_total()
        if final_price > 5000.0:
            return final_price - (final_price*10/100)
    
    def get_extra_discount_amount(self):              
        amount = self.get_total()
        return amount*10/100

    
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=256)
    apartment_address = models.CharField(max_length=256)
    country = CountryField(multiple=False)
    zipcode = models.CharField(max_length=6)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}E-Commerce{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    {% block head %} 
    <!-- BOOTSTRAP LINKS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

    {% endblock %}

</head>
<body>
    {% block body %}
    {% block content  %}
    {% endblock content %}

                <!-- JQuery -->
                <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
                <!-- Bootstrap tooltips -->
                <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
                <!-- Bootstrap core JavaScript -->
                <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
                <!-- MDB core JavaScript -->
                <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
                <!-- Initializations -->
                <script type="text/javascript">
                    // Animations initialization
                    new WOW().init();
                </script>
    {% endblock %}

    {% block extra_body %}
    {% endblock %}
</body>
</html>

templates/checkout-page.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<head>
  <style>
    body{
      list-style-type: none;
    }
  </style>
</head>
{% block content %}


  <!-- Navbar -->
      {% include "navbar.html" %}

  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout Form</h2>

      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">


            <form class="card-body" method="POST">
              {% csrf_token %}

              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                    {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>

                

                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="{{ form.zipcode }">Zipcode</label>
                  {{ form.zipcode }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                {{ form.same_shipping_address }}
                <label for="{{ form.same_shipping_address.label }}">{{ form.same_shipping_address.label }}</label>
              </div>
              <div class="custom-control custom-checkbox">
                {{ form.save_info }}
                <label for="{{ form.save_info.label }}">{{ form.save_info.label }}</label>
              </div>

              <hr>

              <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" value="{{ value }}" name="payment_option" type="radio" class="custom-control-label">
                  <label for="{{ name }}">{{ name }}</label>
                </div>
              {% endfor %}

              </div>

              <!-- card-details.txt -->
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->

 {% include 'footer.html' %} 

{% endblock %}

templates/footer.html
<head>
  <style>
    .custom-class-footer {
      margin-top: 100%;
    }
  </style>
</head>

<!--Footer-->
  <footer class="page-footer text-center font-small wow fadeIn custom-class-footer">

    <!--contact us-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="#" role="button">Link
        <i class="fas fa-phone ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="mailto:#" role="button">Contact us
        <i class="fas fa-envelope ml-2"></i>
      </a>
    </div>
    <!-- /contact us -->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://github.com/Nipun3120" target="_blank"> Nipun Verma </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home-page.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Navbar -->
{% include "navbar.html" %}

  <!--Main layout-->
  <main>
    <div class="container" style="margin-top: 100px;">

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

              {% for item in object_list %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">
                  <!--Card-->
                  <div class="card"  style="height: 400px;">
                    
                    <!--Card image-->
                      
                        <div class="view overlay">
                          {% if item.image.url %}
                            <img src="{{ item.image.url }}" class="card-img-top" alt="">
                            {% endif %}
                          <a href="{{ item.get_absolute_url }}">
                            <div class="mask rgba-white-slight"></div>
                          </a>
                        </div>        
                      
                      <!--Card image-->

                      <!--Card content-->
                      <div class="card-body text-center">
                        <!--Category & Title-->
                        <a href="" class="grey-text">
                          <h5>{{ item.get_category_display }}</h5>
                        </a>
                        <h5>
                          <strong>
                            <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                              <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                            </a>
                          </strong>
                        </h5>

                        <h4 class="font-weight-bold blue-text">
                          <strong>
                            {% if item.discounted_price %}
                              ${{ item.discounted_price }}
                            {% else %}
                              ${{ item.price }}
                            {% endif %}
                          </strong>
                        </h4>
                      </div>
                  </div>
            </div>
               {% endfor %}

        </div>
        <!--Grid row-->

      </section>


      {% if is_paginated %}
      <!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>

            <!-- next arror -->
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
            
          </ul>
        </nav>
      {% endif %}


    </div>
  </main>
  
  {% include 'footer.html' %}

  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

{% endblock %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}
    <h2>list of items</h2>

    
    {% for item in  items %}
        {{ item }}
    {% endfor %}

{% endblock %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}
<div style="margin-top: 70px; padding: 20px;">
  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show " role="alert">
        {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span data-dismiss="true">&times;</span>
      </button>
    </div> 
  {% endfor %}
  {% endif %}
</div>




<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
      <strong class="blue-text">Brand Name</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="{% url 'core:home' %}">home
                <span class="sr-only">(current)</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:check' %}">Checkout</a>
            </li>

            <li class="nav-item">
              <a class="nav-link waves-effect" href="#">Products</a>
            </li>

          </ul>

          <!-- Right -->
          
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:order_summary' %}">                  
                <span class="badge blue z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                  <i class="fas fa-shopping-cart"></i>
                  <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect border border-primary rounded" href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect border rounded ml-3" ><h6>Hello <span style="text-transform: uppercase;">{{ user.username }}</span></h6></a>
            </li>
          </ul>

          {% else %}
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
              <a class="nav-link waves-effect border border-primary rounded" href="{% url 'account_login' %}">Login</a>
            </li>
          </ul>

          {% endif %}
    </div>

  </div>
</nav>

templates/order_summary.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- navbar -->
{% include 'navbar.html' %}

<main>
    <div class="container">

        <h2>Order Summary</h2>
        <div class="table-responsive text-nowrap">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Discount Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr style="background-color: whitesmoke;">
                        
                        <td scope="row">{{ forloop.counter }}</td>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            {% if order_item.item.discounted_price %}
                                $ {{ order_item.item.discounted_price }}
                            {% else %}
                                $ 0.0
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'core:decrease_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:increase_item_in_cart' order_item.item.slug%}"><i class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discounted_price %}
                                $ {{ order_item.get_total_price_discount }}
                            {% else %}
                                $ {{ order_item.get_total_price }}
                            {% endif %}
                            <a href="{% url 'core:remove_from_cart' order_item.item.slug %}">
                                <i class="fas fa-trash-alt float-right"></i>
                            </a>
                        </td>


                    </tr>

                    {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">
                            <h5>Your Cart Is Empty</h5>
                        </td>
                    </tr>
                    <tr>
                    <td colspan="6">
                        <a href="{% url 'core:home' %}" class="btn btn-danger float-right">Continue Shopping</a>
                    </td>
                    </tr>

                    {% endfor %}

                    {% if object.get_total %}
                    <tr>
                        <td></td>
                        <td colspan="4" style="font-weight: 700;">Total price</td>
                        <td style="color: #2196f3; font-weight: 500;">$ {{ object.get_total }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan="4"><strong>You save</td>
                        <td>$ {{ object.get_total_actual }}</td>
                    </tr>

                    {% if object.get_extra_discount %}
                    <tr>
                        <td></td>
                        <td colspan="4"><strong>Extra Discount</td>
                        <td>$ {{ object.get_extra_discount_amount }}&nbsp;(10%)</td>
                    </tr>
                    
                    <tr>
                        <td></td>
                        <td colspan="4" style="font-weight: 500;"><strong>Grand Total</td>
                        <td style="font-weight: 500;" class="text-primary">$ {{ object.get_extra_discount }}</td>
                    </tr>
                    {% endif %}

                    <tr>
                        <td colspan="6">
                            <a href="{% url 'core:home' %}" class="btn btn-primary">Continue Shopping</a>
                            <a href="{% url 'core:check' %}" class="btn btn-success float-right">Proceed To Checkout</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>


        </div>
        

    </div>
</main>


<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

templates/payment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<head>
  <style>
    body{
      list-style-type: none;
    }
  </style>
</head>
{% block content %}


  <!-- Navbar -->
      {% include "navbar.html" %}

<main>
    <div class="container">
        <h2 class="my-5 h2 text-center">Payment</h2>
        <div class="row">
            <div class="col-md-12 mb-4">
                <div class="card">
                    <form action="" method="post" class="card-body">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

  <!--Footer-->
 {% include 'footer.html' %} 

{% endblock %}

templates/product.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- navbar -->
{% include 'navbar.html' %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5" >

      <div class="row wow fadeIn">

        <div class="col-md-6 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="" >

        </div>

        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <h3 style="margin-top: 10px;">{{ item.title }}</h3>
            </div>

            <p class="lead">

              {% if item.discounted_price %}
                <span class="mr-1">
                  price: <del>${{ item.price }}</del>
                </span>
                <span>${{ item.discounted_price }}</span>
              {% else %}
                <span>price:  ${{ item.price }}</span>
              {% endif %}
            </p>

            {% if item.description %}
              <p class="lead font-weight-bold">Description</p>
              <p>{{ item.description }}</p>
            {% else %}
              {{ NULL }}
            {% endif %}
            
            <!--
            <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </form> -->

            <a href="{% url 'core:add_to_cart' item.slug %}" class="btn btn-primary btn-md my-0 p"> 
              Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
      </div>

      <!-- similar products -->
      <div class="row wow fadeIn">
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="{% static 'img/items/smartphone.jpg' %}" class="img-fluid" alt="">
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <img src="{% static 'img/items/lenovo-ideapad.jpg' %}" class="img-fluid" alt="">
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <img src="{% static 'img/items/smartphone-2.jpg' %}" class="img-fluid" alt="">
        </div>
      </div>
    </div>
  </main>
  

    <!-- footer -->
      {% include 'footer.html' %}



{% endblock %}